server:
  port: 10001
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./data/payments-ha.db;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
